In [1]:
import pandas as pd
from pathlib import Path
import datetime

In [2]:
raw_df = pd.read_csv(Path("../Resources/Mental_Health_Care_in_the_Last_4_Weeks.csv"))
raw_df.head()

,Indicator,Group,State,Subgroup,Phase,Time Period,Time Period Label,Time Period Start Date,Time Period End Date,Value,LowCI,HighCI,Confidence Interval,Quartile Range,Suppression Flag
0,Took Prescription Medication for Mental Health...,National Estimate,United States,United States,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4,19.0,19.8,19.0 - 19.8,NaN,NaN
1,Took Prescription Medication for Mental Health...,By Age,United States,18 - 29 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7,17.2,20.3,17.2 - 20.3,NaN,NaN
2,Took Prescription Medication for Mental Health...,By Age,United States,30 - 39 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3,17.3,19.2,17.3 - 19.2,NaN,NaN
3,Took Prescription Medication for Mental Health...,By Age,United States,40 - 49 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4,19.5,21.3,19.5 - 21.3,NaN,NaN
4,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,2,13,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2,20.2,22.2,20.2 - 22.2,NaN,NaN

In [3]:
del raw_df['Phase']
del raw_df['Time Period']
del raw_df['LowCI']
del raw_df['HighCI']
del raw_df['Confidence Interval']
del raw_df['Quartile Range']
del raw_df['Suppression Flag']
raw_df.head()

,Indicator,Group,State,Subgroup,Time Period Label,Time Period Start Date,Time Period End Date,Value
0,Took Prescription Medication for Mental Health...,National Estimate,United States,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4
1,Took Prescription Medication for Mental Health...,By Age,United States,18 - 29 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7
2,Took Prescription Medication for Mental Health...,By Age,United States,30 - 39 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3
3,Took Prescription Medication for Mental Health...,By Age,United States,40 - 49 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4
4,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2

In [4]:
cdc_national_biweekly = raw_df
cdc_national_biweekly=cdc_national_biweekly[['Indicator', 'Group', 'Subgroup', 'Time Period Label', 'Time Period Start Date', 'Time Period End Date', 'Value']]
cdc_national_biweekly.head()

,Indicator,Group,Subgroup,Time Period Label,Time Period Start Date,Time Period End Date,Value
0,Took Prescription Medication for Mental Health...,National Estimate,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4
1,Took Prescription Medication for Mental Health...,By Age,18 - 29 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7
2,Took Prescription Medication for Mental Health...,By Age,30 - 39 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3
3,Took Prescription Medication for Mental Health...,By Age,40 - 49 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4
4,Took Prescription Medication for Mental Health...,By Age,50 - 59 years,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2

In [5]:
cdc_national_biweekly.to_csv("../Resources/cdc_national_biweekly.csv", index=False, header=True)

In [6]:
cdc_statutory_biweekly = raw_df
cdc_statutory_biweekly=cdc_statutory_biweekly[['Indicator', 'State', 'Time Period Label', 'Time Period Start Date', 'Time Period End Date', 'Value']]
cdc_statutory_biweekly.head()

,Indicator,State,Time Period Label,Time Period Start Date,Time Period End Date,Value
0,Took Prescription Medication for Mental Health...,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,19.4
1,Took Prescription Medication for Mental Health...,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.7
2,Took Prescription Medication for Mental Health...,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,18.3
3,Took Prescription Medication for Mental Health...,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,20.4
4,Took Prescription Medication for Mental Health...,United States,"Aug 19 - Aug 31, 2020",08/19/2020,08/31/2020,21.2

In [7]:
cdc_statutory_biweekly.to_csv("../Resources/cdc_statutory_biweekly.csv", index=False, header=True)

In [8]:
cdc_annual = raw_df
cdc_annual['Year'] = cdc_annual['Time Period Start Date'].str[-4:].apply(int)
cdc_annual=cdc_annual[['Indicator', 'Group', 'State', 'Subgroup', 'Year', 'Value']]
cdc_annual.head()

,Indicator,Group,State,Subgroup,Year,Value
0,Took Prescription Medication for Mental Health...,National Estimate,United States,United States,2020,19.4
1,Took Prescription Medication for Mental Health...,By Age,United States,18 - 29 years,2020,18.7
2,Took Prescription Medication for Mental Health...,By Age,United States,30 - 39 years,2020,18.3
3,Took Prescription Medication for Mental Health...,By Age,United States,40 - 49 years,2020,20.4
4,Took Prescription Medication for Mental Health...,By Age,United States,50 - 59 years,2020,21.2

In [9]:
cdc_statutory_annual = cdc_annual.groupby(["Indicator", "State", "Year"])['Value'].mean().reset_index().sort_values("Year").reset_index()
cdc_statutory_annual = cdc_statutory_annual[["Indicator", "State", "Year","Value"]]
cdc_statutory_annual.head()

,Indicator,State,Year,Value
0,Needed Counseling or Therapy But Did Not Get I...,Alabama,2020,10.577778
1,Took Prescription Medication for Mental Health...,North Carolina,2020,21.288889
2,"Received Counseling or Therapy, Last 4 Weeks",Arkansas,2020,7.111111
3,"Received Counseling or Therapy, Last 4 Weeks",California,2020,10.200000
4,Took Prescription Medication for Mental Health...,Kansas,2020,25.866667

In [10]:
cdc_statutory_annual.to_csv("../Resources/cdc_statutory_annual.csv", index=False, header=True)

In [11]:
cdc_national_annual = cdc_annual.groupby(["Indicator", "Group", "Subgroup", "Year"])['Value'].mean().reset_index().sort_values("Year").reset_index()
cdc_national_annual = cdc_national_annual[["Indicator", "Group", "Subgroup", "Year","Value"]]
cdc_national_annual.head()

,Indicator,Group,Subgroup,Year,Value
0,Needed Counseling or Therapy But Did Not Get I...,By Age,18 - 29 years,2020,18.811111
1,"Received Counseling or Therapy, Last 4 Weeks",By State,Minnesota,2020,10.122222
2,"Received Counseling or Therapy, Last 4 Weeks",By State,Michigan,2020,9.088889
3,Took Prescription Medication for Mental Health...,By State,District of Columbia,2020,18.311111
4,"Received Counseling or Therapy, Last 4 Weeks",By State,Massachusetts,2020,14.255556

In [12]:

cdc_national_annual.to_csv("../Resources/cdc_national_annual.csv", index=False, header=True)